### PR TITLE
CashFlow constructor period override

### PR DESCRIPTION
**Pull request by recurrence**
Hi @tubedude ,  I needed to be able to adjust the period so I modified Cashflow and Base to fit.  What do you think?

1.  Prepends new period argument with DAYS_IN_YEAR default to Cashflow initialize.
2.  Adds verifying unit test.
3.  Version bump due to the potentially breaking change.

### CODE REVIEW

**Comment by tubedude** [comment]
First of all sorry for the delay: I was on vacations with a lousy connection. 
Second: thanks for the interest in the gem. I thought I was developing for myself only and I'm proud it is useful for someone else. 

Now down to business: I don't like the way I was going with the initializer. What do you think of making it a hash initializer so you would

**Comment by tubedude** [comment]
So you would initialize:
Cashflow.new flow: array_of_transactions, period: 360, compact: true. 

What do you think?

**Comment by recurrence** [comment]
Sounds great!

:+1:

**Comment by recurrence** [comment]
Closing this PR since the alternative implementation is now in mainline and it looks good!  :+1:

**Pull request closed without merging**
