### PR TITLE
Remove ruby inline and c function call

### PR DESCRIPTION
**Pull request by recurrence**
Is there a particular reason to use C over ruby here?  Doesn't seem to be having an appreciable impact on performance and ruby inline is a pain in some environments due to its' filesystem access.

### CODE REVIEW

**Comment by tubedude** [comment]
In my experience it has a huge impact to have it as C. I'll run some benchmarks.

**Comment by chrisnicola** [comment]
@tubedude I think I figured out why you are probably seeing an impact. 

If you are passing in BigDecimal values then Ruby is doing the computation via BigDecimal which is an order of magnitude slower than with floats. However since Ruby math functions are already implemented in C I would highly doubt if inlining this bit of code will make any difference if you are comparing it with Ruby floats.

**Comment by tubedude** [comment]
@maciej-szlosarczyk what do you think? 
In practice I have a huge gain with inline C. But if the slowness is due to Decimal, maybe we can give it a try.

**Comment by maciej-szlosarczyk** [comment]
Hey @tubedude, @recurrence,

I don't see a huge benefit from inline C code. A naive test does not yield any significant difference between Ruby and C when operating on floats with Ruby 2.2.2:
```
                user     system      total        real
R version   0.000000   0.000000   0.000000 (  0.000055)
Rehearsal ---------------------------------------------
R version   0.000000   0.000000   0.000000 (  0.000078)
------------------------------------ total: 0.000000sec

                user     system      total        real
R version   0.000000   0.000000   0.000000 (  0.000334)
Rehearsal ---------------------------------------------
R version   0.000000   0.000000   0.000000 (  0.000151)
------------------------------------ total: 0.000000sec

                user     system      total        real
R version   0.000000   0.000000   0.000000 (  0.000074)
Rehearsal ---------------------------------------------
R version   0.000000   0.000000   0.000000 (  0.000109)
------------------------------------ total: 0.000000sec

                user     system      total        real
R version   0.000000   0.000000   0.000000 (  0.000323)
Rehearsal ---------------------------------------------
R version   0.000000   0.000000   0.000000 (  0.000407)
------------------------------------ total: 0.000000sec

                user     system      total        real
R version   0.000000   0.000000   0.000000 (  0.000074)
Rehearsal ---------------------------------------------
R version   0.000000   0.000000   0.000000 (  0.000127)
------------------------------------ total: 0.000000sec
```

```
                user     system      total        real
c version   0.000000   0.000000   0.000000 (  0.000088)
Rehearsal ---------------------------------------------
c version   0.000000   0.000000   0.000000 (  0.000040)
------------------------------------ total: 0.000000sec

                user     system      total        real
c version   0.000000   0.000000   0.000000 (  0.000104)
Rehearsal ---------------------------------------------
c version   0.000000   0.000000   0.000000 (  0.000032)
------------------------------------ total: 0.000000sec

                user     system      total        real
c version   0.000000   0.000000   0.000000 (  0.000203)
Rehearsal ---------------------------------------------
c version   0.000000   0.000000   0.000000 (  0.000153)
------------------------------------ total: 0.000000sec

                user     system      total        real
c version   0.000000   0.000000   0.000000 (  0.000524)
Rehearsal ---------------------------------------------
c version   0.000000   0.000000   0.000000 (  0.000244)
------------------------------------ total: 0.000000sec

                user     system      total        real
c version   0.000000   0.000000   0.000000 (  0.000084)
Rehearsal ---------------------------------------------
c version   0.000000   0.000000   0.000000 (  0.000039)
------------------------------------ total: 0.000000sec
```

In comparison, a BigDecimal version is indeed very slow and does not even finish the test:
```
                         user     system      total        real
BigDecimal version   0.010000   0.000000   0.010000 (  0.009720)
Rehearsal ------------------------------------------------------
BigDecimal version   0.010000   0.000000   0.010000 (  0.004697)
--------------------------------------------- total: 0.010000sec

                         user     system      total        real
BigDecimal version   0.000000   0.000000   0.000000 (  0.009962)
Rehearsal ------------------------------------------------------
BigDecimal version   0.010000   0.000000   0.010000 (  0.006737)
--------------------------------------------- total: 0.010000sec

                         user     system      total        real
BigDecimal version   0.010000   0.000000   0.010000 (  0.010073)
Rehearsal ------------------------------------------------------
BigDecimal version   0.010000   0.000000   0.010000 (  0.006282)
--------------------------------------------- total: 0.010000sec

                         user     system      total        real
BigDecimal version   0.000000   0.000000   0.000000 (  0.011420)
Rehearsal ------------------------------------------------------
BigDecimal version   0.010000   0.000000   0.010000 (  0.007386)
--------------------------------------------- total: 0.010000sec

                         user     system      total        real
BigDecimal version   0.010000   0.000000   0.010000 (  0.003728)
Rehearsal ------------------------------------------------------
BigDecimal version   0.010000   0.000000   0.010000 (  0.006073)
--------------------------------------------- total: 0.010000sec
```

**Pull request closed without merging**
